### ISSUE TITLE
About CPU Pin

### ISSUE THREAD

**Issue by BurlyLuo** [cndoit18/lxcfs-on-kubernetes#5]
use this template:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: httpd:2.4.32
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "2"
            limits:
              memory: "256Mi"
              cpu: "2"
```
if we deploy in this metorthd, we still can view all the cpu in the pod. 
Like:
```
root@web-5f859c87cf-5wzhm:/usr/local/apache2# top
top - 13:00:18 up  3:57,  0 users,  load average: 0.86, 0.69, 0.65
Tasks:   6 total,   1 running,   5 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  1.0 us,  0.0 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:    262144 total,    13336 used,   248808 free,        0 buffers
KiB Swap:        0 total,        0 used,        0 free.      264 cached Mem
```
if we add the cpu pin featuer in the kunbernetes cluster, we can get a good environment.
Like:
```
bash-4.2# taskset -cp 1
pid 1's current affinity list: 20,22,64,66
bash-4.2# free -mh 
              total        used        free      shared  buff/cache   available
Mem:            16G        3.4G        7.2G          0B        5.4G         12G
Swap:            0B          0B          0B
bash-4.2# top 
top - 13:01:43 up  6:57,  0 users,  load average: 17.88, 19.84, 20.87
Tasks:  40 total,   1 running,  39 sleeping,   0 stopped,   0 zombie
%Cpu0  : 20.9 us, 20.9 sy,  0.0 ni, 58.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  : 50.0 us, 50.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : 50.0 us, 50.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 50.0 us, 50.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
```
